os: mac
tag: browser
browser.host: app.slack.com
-
(go [to] | section | zone) next: key(f6)
(go [to] | section | zone) (previous | last): key(shift-f6)
go [to] messages: key(cmd-shift-k)
go (next | forth): key("cmd-]")
go (last | back | previous): key("cmd-[")
go [to] people [and user groups]: key(cmd-shift-e)
go [to] (unread | unreads): key(cmd-shift-a)
mark [messages] as read: key(esc)
mark all [messages] [as] read: key(shift-esc)
go [to] channels: user.messaging_open_channel_picker()
go [to] unread next: key(alt-shift-down)
go up: key(up)
go down: key(down)
edit (message | last): key(up)
message edit: key(up)
message send: key(enter)
(format command | [format] commandify): key(cmd-shift-c)
(format code | [format] codify): key(cmd-alt-shift-c)
[format] (bullet | bulleted) list: key(cmd-shift-8)
[format] (number | numbered) list: key(cmd-shift-7)
(format quotes | format quotation | [format] quotify): user.slack_insert_quotation()
(format bold | [format] boldify): key(cmd-b)
(format italic | [format] italify): key(cmd-i)
(format strike | format strikethrough | [format] strikify): key(cmd-shift-x)
(format link | [format] linkify): key(cmd-shift-u)
[format] snippet: key(cmd-shift-enter)
(huddle | call) (new | join):
    key(cmd-shift-h)
(huddle | call) close: key(cmd-shift-h)
keyboard shortcuts: key(cmd-/)
