app: claude_desktop
-

# Conversations
(chat | convo | thread) new: key(ctrl-n)

# Sidebar / navigation
(sidebar | menu) toggle: key(ctrl-b)
search: key(ctrl-k)
preview toggle: key(ctrl-shift-p)
diff toggle: key(ctrl-shift-d)
terminal toggle: key(ctrl-`)
go (next | forth): key(alt-right)
go (last | back | previous): key(alt-left)

# Submission / cancellation
message send: key(enter)
message cancel: key(esc)
stop generating: key(esc)
# focus input: key(ctrl-shift-;)  # not the correct shortcut yet

# Slash commands
# Full reference: https://code.claude.com/docs/en/commands
slash help: insert("/help")
slash by the way: insert("/btw")
slash remote control: insert("/remote-control")
slash clear: insert("/clear")
slash init: insert("/init")
slash mcp: insert("/mcp")
slash compact: insert("/compact")
slash model: insert("/model")
slash config: insert("/config")
slash plan: insert("/plan")
slash resume: insert("/resume")
slash rewind: insert("/rewind")
slash usage: insert("/usage")
slash review: insert("/review")
slash context: insert("/context")
slash agents: insert("/agents")
slash memory: insert("/memory")
slash diff: insert("/diff")

skill animation vocabulary: insert("/animation-vocabulary")
skill ask matt: insert("/ask-matt")
skill batch grill me: insert("/batch-grill-me")
skill claude hand off: insert("/claude-handoff")
skill code review: insert("/code-review")
skill codebase design: insert("/codebase-design")
skill design an interface: insert("/design-an-interface")
skill diagnosing bugs: insert("/diagnosing-bugs")
skill domain modeling: insert("/domain-modeling")
skill edit article: insert("/edit-article")
skill emil design engineering: insert("/emil-design-eng")
skill git guardrails claude code: insert("/git-guardrails-claude-code")
skill grill me: insert("/grill-me")
skill grill with docs: insert("/grill-with-docs")
skill grilling: insert("/grilling")
skill hand off: insert("/handoff")
skill implement: insert("/implement")
skill improve: insert("/improve")
skill improve animations: insert("/improve-animations")
skill improve codebase architecture: insert("/improve-codebase-architecture")
skill loop me: insert("/loop-me")
skill migrate to shoehorn: insert("/migrate-to-shoehorn")
skill obsidian vault: insert("/obsidian-vault")
skill prototype: insert("/prototype")
skill quality assurance: insert("/qa")
skill request refactor plan: insert("/request-refactor-plan")
skill research: insert("/research")
skill resolving merge conflicts: insert("/resolving-merge-conflicts")
skill review animations: insert("/review-animations")
skill scaffold exercises: insert("/scaffold-exercises")
skill setup matt pocock skills: insert("/setup-matt-pocock-skills")
skill setup pre commit: insert("/setup-pre-commit")
skill setup typescript deep modules: insert("/setup-ts-deep-modules")
skill test driven development: insert("/tdd")
skill teach: insert("/teach")
skill to questionnaire: insert("/to-questionnaire")
skill to spec: insert("/to-spec")
skill to tickets: insert("/to-tickets")
skill triage: insert("/triage")
skill ubiquitous language: insert("/ubiquitous-language")
skill wayfinder: insert("/wayfinder")
skill web design guidelines: insert("/web-design-guidelines")
skill wizard: insert("/wizard")
skill zutobi commenter: insert("/zutobi-commenter")

# App
settings open: key(ctrl-comma)
keyboard shortcuts: key(ctrl-/)
reload it: key(ctrl-r)
zoom in: key(ctrl-=)
zoom out: key(ctrl--)
zoom reset: key(ctrl-0)
